default: &default
  host: localhost
  adapter: sqlite3
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: db/diario_development.sqlite3

test:
  <<: *default
  database: db/diario_test.sqlite3

production:
  <<: *default
  database: db/diario.sqlite3
