default: &default
  host: localhost
  adapter: sqlite3
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: db/puntapie_development.sqlite3

test:
  <<: *default
  database: db/puntapie_test.sqlite3

production:
  <<: *default
  database: db/puntapie.sqlite3
